### PR TITLE
Add builder tests

### PR DESCRIPTION
**Pull request by heatsink**
Added massive tests for the builder class

### CODE REVIEW

**Comment by AndiAndreas** [comment]
Code ist okay. Lets await travis

**Comment by AndiAndreas** [comment]
04:00 +125 -1: /home/travis/build/mobileappdevhm/dev-team-1-cie-app-in-flutter/test/widgets/courseList_test.dart: 2 course_description                                                                 04:04 +125 -1: /home/travis/build/mobileappdevhm/dev-team-1-cie-app-in-flutter/test/widgets/courseList_test.dart: 2 course_description

**Comment by heatsink** [comment]
Been looking at the log, not yet sure why there would be an error there. I'l try close & reopen to trigger a rebuild.

**Comment by heatsink** [comment]
¯\_(ツ)_/¯

**Pull request merged**
