### PR TITLE
Course history page

### PR DESCRIPTION
**Pull request by heatsink**
Disclaimer: This will probably wreck our code coverage for now lol

Please check the branch out and test on your device before merging!

The UI isn't fully done yet, this pull request is only for the heavy functionality.

### CODE REVIEW

**Comment by heatsink** [comment]
Oh yeah, I have a lot of asynchronous moving parts so I commented out the tests for the course history page for now.

Even with that commented out, to retain a good code coverage more tests will be necessary to add later.

**Comment by heatsink** [comment]
Here's some screenshots
screen shot 2018-07-03 at 11 49 35 pm
screen shot 2018-07-03 at 11 49 49 pm
screen shot 2018-07-03 at 11 49 56 pm
screen shot 2018-07-03 at 11 50 10 pm
screen shot 2018-07-03 at 11 49 41 pm

**Comment by RedTo** [comment]
Awesome! Great job!!!

I will test and review later that day.

**Comment by RedTo** [comment]
I found a little bug...

`E/flutter (11382): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (11382): NoSuchMethodError: The getter 'length' was called on null.
E/flutter (11382): Receiver: null
E/flutter (11382): Tried calling: length
E/flutter (11382): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
E/flutter (11382): #1      _parseJson (dart:convert/runtime/libconvert_patch.dart:28:28)
E/flutter (11382): #2      JsonDecoder.convert (dart:convert/json.dart:542:36)
E/flutter (11382): #3      JsonCodec.decode (dart:convert/json.dart:169:41)
E/flutter (11382): #4      _AddTakenCoursesState.initState.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:cie_team1/views/addTakenCourses.dart:54:51)
E/flutter (11382): #5      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (11382): #6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (11382): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (11382): #8      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (11382): #9      Future._complete (dart:async/future_impl.dart:467:7)
E/flutter (11382): #10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (11382): #11     FileStore.readFileAsString (package:cie_team1/utils/fileStore.dart)
E/flutter (11382): <asynchronous suspension>
E/flutter (11382): #12     _AddTakenCoursesState.initState.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:cie_team1/views/addTakenCourses.dart:53:25)
E/flutter (11382): #13     State.setState (package:flutter/src/widgets/framework.dart:1125:30)
E/flutter (11382): #14     _AddTakenCoursesState.initState.<anonymous closure>.<anonymous closure> (package:cie_team1/views/addTakenCourses.dart:52:13)
E/flutter (11382): #15     _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (11382): #16     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (11382): #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (11382): #18     Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (11382): #19     Future._complete (dart:async/future_impl.dart:467:7)
E/flutter (11382): #20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (11382): #21     NineAPIEngine.getJsonMulti (package:cie_team1/utils/nineAPIConsumer.dart)
E/flutter (11382): <asynchronous suspension>
E/flutter (11382): #22     _AddTakenCoursesState.initState.<anonymous closure> (package:cie_team1/views/addTakenCourses.dart:51:25)
E/flutter (11382): #23     _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (11382): #24     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (11382): #25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (11382): #26     Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (11382): #27     Future._complete (dart:async/future_impl.dart:467:7)
E/flutter (11382): #28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (11382): #29     FileStore.readFileAsString (package:cie_team1/utils/fileStore.dart)
E/flutter (11382): <asynchronous suspension>
E/flutter (11382): #30     _AddTakenCoursesState.initState (package:cie_team1/views/addTakenCourses.dart:33:17)
E/flutter (11382): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
E/flutter (11382): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (11382): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (11382): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (11382): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (11382): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (11382): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (11382): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (11382): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (11382): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter (11382): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (11382): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (11382): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (11382): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (11382): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (11382): #46     Element.u`

Maybe the problem is, that I do not have any course data yet... But if I try to pull down new course data on Courses there is no data loaded.

**Comment by RedTo** [comment]
Basically I'm not able to get any course data on this branch. Maybe that's the main reason.

**Comment by RedTo** [comment]
Got it, Nine is having a problem: https://nine.wi.hm.edu/api/v2/courses/FK%2013/CIE/SoSe%2018 return an empty array...

**Comment by RedTo** [comment]
closed during implementation in other PR (following)

**Pull request closed without merging**
