### PR TITLE
Major dropdown and search feature

### PR DESCRIPTION
**Pull request by heatsink**
- Implemented a dropdown to filter courses by department
- Implemented search functionality to search for courses by typing when activated. Will file an issue to use a real search algorithm like the Boyer–Moore algorithm or something.
- Refactored some of our mocks so more courses could be added.
- Also made some of the tests less hard-coded so we could change our mocks without too much of a headache.
- Otherwise nothing too crazy!

### CODE REVIEW

**Comment by heatsink** [comment]
screen shot 2018-05-28 at 9 41 17 pm
screen shot 2018-05-28 at 9 41 24 pm
screen shot 2018-05-28 at 9 41 09 pm
screen shot 2018-05-28 at 9 42 09 pm
screen shot 2018-05-28 at 9 41 05 pm
screen shot 2018-05-28 at 9 41 36 pm
Here's some screenshots!

**Comment by heatsink** [comment]
So I kind of just eyeballed my ideas into this so the UI is still relatively rudimentary. 
- Please discuss improvements for UI in https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/75
Thanks!

**Comment by RedTo** [comment]
Can this branch be deleted?

**Comment by heatsink** [comment]
(not yet but very soon), I submitted another pull request from this branch adding a few more tests!

**Pull request merged**
