### PR TITLE
Pull request for theme discussion

### PR DESCRIPTION
**Pull request by heatsink**
Discuss if you guys like this better (or if you have other ideas for theme improvements).

Issue for discussion here:
https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/138
screen shot 2018-06-19 at 9 56 46 am

### CODE REVIEW

**Comment by AndiAndreas** [comment]
Not sure if red is the color which should dominate. Looks good but im not sure if this fits other pages as well.

**Comment by RedTo** [comment]
Can you please explain why we should approve this pull request?

You referenced a discussion issue, where nobody has written something. Please don't get me wrong, but I think that there are maybe more things to discuss, before we should pull this in master.

**Comment by AndiAndreas** [comment]
But it still looks better than the gray one. Red fits the other views best but im not sure im red should domite the scrren.

**Comment by heatsink** [comment]
I didn't mean for this pull request to be approved immediately, and I meant for it to be part of the ongoing discussion. I just made it a pull request since we're running out of time and figured one or two rounds of comments would be enough. 

The change appears more controversial than I thought it would be though, so I'm going to close this for now. Please make suggestions or comments in the issue posted! #138

**Comment by RedTo** [comment]
Let's reopen it again. I'm sorry for confusion...

**Pull request merged**
