### PR TITLE
Firebase analytics

### PR DESCRIPTION
**Pull request by orb1005**
take a look at my issue to see what kind of tracking code I've implemented

### CODE REVIEW

**Comment by orb1005** [comment]
@AndiAndreas let me check that. I didn't add the file by myself

**Comment by orb1005** [comment]
@AndiAndreas found it. The file gets created when you run flutter test --coverage. Can be deleted

**Comment by AndiAndreas** [comment]
Nice. Then we can add it to .gitignore?

**Comment by orb1005** [comment]
@AndiAndreas yes if you want to

**Comment by orb1005** [comment]
@AndiAndreas WTF no travis failed. I don't get it

**Comment by orb1005** [comment]
@AndiAndreas Does that test which it fails at have a too short timeout?

**Comment by AndiAndreas** [comment]
Always when its last commit before bed time. 🤣

**Comment by orb1005** [comment]
@AndiAndreas Don't know what I should change now. That fail isn't related to my code

**Comment by orb1005** [comment]
image
Test is green when I run it locally. It's just because travis is fu**ing slow

**Comment by AndiAndreas** [comment]
Maybe try again and if it doesn't work set test to ignore for now.

**Pull request merged**
